---
- hosts: all
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_user: root
  
  tasks:
    - name: Extract target domain names
      local_action: ansible.builtin.shell echo "{{ ssl_cert_content }}" | openssl x509 -text -noout | grep DNS | tr -d ' ' | tr -d 'DNS:' | sed -e "s/,/ /g"
      register: domain_names
    - debug: msg="{{ domain_names }}"
