---
- hosts: all
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_user: root
  
  tasks:
  - name: Create test file in the ubuntu home directory
    shell: echo "{{ input_text }}" > /home/ubuntu/test.txt
