---
- hosts: all
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_user: root
  
  tasks:
  - name: Create test file in the home directory
    command: echo "{{ input_text }}" > ~/test.txt
